#!/bin/bash
mkdir -p export
for i in `ls src/*.{h,c,r}`; do
    tr '\n' '\r' < $i | iconv -f UTF-8 -t MACINTOSH > export/${i#src/}
done
tr '\n' '\r' < README.md | iconv -f UTF-8 -t MACINTOSH > export/README
